insert into LACQUER
(INTERNAL_ID, LACQUER_CODE, LACQUER_NAME, LACQUER_POPULARITY, LACQUER_BRAND)
values
(UUID(), 'A07', 'NIEBIESKA MISTIC', '1', 'BMW'),
(UUID(), 'A08', 'SILVER GREY METALLIC', '2', 'BMW'),
(UUID(), 'A11', 'HIGHLAND GRUEN', '3', 'BMW'),
(UUID(), 'A17', 'HAVANNA EFFECT', '4', 'BMW'),
(UUID(), 'A18', 'QUARTZ BLAU', '5', 'BMW'),
(UUID(), 'A19', 'SYDNEY BLAU', '6', 'BMW'),
(UUID(), 'A21', 'NAUTIKBLAU', '1', 'BMW'),
(UUID(), 'A22', 'SPARKLING GRAFIT/GRAFITOWY= HC Hyundai', '2', 'BMW'),
(UUID(), 'A34', 'ARKTIS EFFECT', '2', 'BMW'),
(UUID(), 'A35', 'MONACO BLAU', '2', 'BMW'),
(UUID(), 'A36', 'TITAN GRAU II', '2', 'BMW'),
(UUID(), 'A51', 'MONTEGO BLAU', '2', 'BMW'),
(UUID(), 'A52', 'KOSMIC GRAU', '2', 'BMW'),
(UUID(), 'A53', 'PLATIN BRONZE', '5', 'BMW'),
(UUID(), 'A55', 'CHROMSILBER', '4', 'BMW'),
(UUID(), 'A61', 'KARMESIN ROT', '3', 'BMW'),
(UUID(), 'C1W', 'WHITE PEARL', '4', 'CADILLAC'),
(UUID(), 'PXR', 'BRILLANT BLACK', '1', 'CHRYSLER'),
(UUID(), 'PPS', 'MALLARD BLUE', '1', 'CHRYSLER');
